#!/usr/bin/env python3
"""Build the CVR Engineering Phase 2 forecast workbook.

Driver-based re-forecast, July 2026 - December 2027, built on the Phase 1
baseline (see build_phase1_workbook.py). The engine:

  revenue        = FTE x hrs/mo x utilization x blended card rate x realization
  direct labor   = FTE x wage/mo x direct-charge share (GL convention: ~92%)
  burden         = wages x 33.8% (GL H1)
  other opex     = H1 run rate; overhead $17,250/mo flat; interest on parent note

Scenario paths (Base / Upside / Downside) drive FTE, utilization, and
realization per month; a selector cell switches the whole model live.
Backlog (remaining PO value on active jobs) and probability-weighted pipeline
provide the booked-work coverage check against forecast revenue.

Output: model/CVR_Model_Phase2_Forecast.xlsx
"""

import os

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

NAVY = "1F3864"
INPUT_BLUE = "0070C0"
FLAG_ORANGE = "C55A11"
GREY = "F2F2F2"

F_TITLE = Font(bold=True, size=14, color=NAVY)
F_H = Font(bold=True, color="FFFFFF")
F_SUB = Font(bold=True, color=NAVY)
F_INPUT = Font(color=INPUT_BLUE)
F_FLAG = Font(color=FLAG_ORANGE, italic=True)
F_NOTE = Font(italic=True, size=9, color="595959")
FILL_H = PatternFill("solid", fgColor=NAVY)
FILL_TOT = PatternFill("solid", fgColor=GREY)
THIN = Side(style="thin", color="BFBFBF")
BOX = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

KFMT = '#,##0.0;(#,##0.0)'
PCT = '0.0%'
HRS = '#,##0'

MONTHS = ["Jul-26", "Aug-26", "Sep-26", "Oct-26", "Nov-26", "Dec-26",
          "Jan-27", "Feb-27", "Mar-27", "Apr-27", "May-27", "Jun-27",
          "Jul-27", "Aug-27", "Sep-27", "Oct-27", "Nov-27", "Dec-27"]
NM = len(MONTHS)          # 18 -> columns B..S
H2_COL = 2 + NM           # T = H2-2026 subtotal (Jul..Dec 26)
FY27_COL = 3 + NM         # U = FY-2027 subtotal

# --------------------------------------------------------- scenario paths ---
BASE_FTE = [10, 10, 10, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13]
UP_FTE   = [10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 15, 16, 16, 16, 16, 16, 16]
DN_FTE   = [10] * 18
BASE_UTIL = [0.60, 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.70,
             0.70, 0.70, 0.70, 0.70, 0.70, 0.70, 0.70]
UP_UTIL   = [0.62, 0.64, 0.66, 0.68, 0.70, 0.71, 0.72, 0.73, 0.74, 0.75, 0.75,
             0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75]
DN_UTIL   = [0.59] * 6 + [0.60] * 12
BASE_REAL = [0.80, 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.90,
             0.90, 0.90, 0.90, 0.90, 0.90, 0.90, 0.90]
UP_REAL   = [0.82, 0.84, 0.86, 0.88, 0.90, 0.91, 0.92, 0.93, 0.94, 0.95, 0.95,
             0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]
DN_REAL   = [0.79] * 6 + [0.80] * 12

# H1 2026 actuals ($K) — anchors from the GL statements
H1 = {"rev": 551.0, "gp": 122.5, "oi": -290.5, "int": 30.1, "ni": -320.5,
      "note_open": 3436.6, "ar_open": 139.8}
BUDGET_FY26 = {"rev": 2029.1, "gp": 1249.4, "ni": 139.4}


def header(ws, row, cols, labels):
    for c, label in zip(cols, labels):
        cell = ws.cell(row=row, column=c, value=label)
        cell.font = F_H
        cell.fill = FILL_H
        cell.alignment = Alignment(horizontal="center", wrap_text=True)
        cell.border = BOX


def title(ws, text, sub=None):
    ws["A1"] = text
    ws["A1"].font = F_TITLE
    if sub:
        ws["A2"] = sub
        ws["A2"].font = F_NOTE


def widths(ws, spec):
    for col, w in spec.items():
        ws.column_dimensions[col].width = w


def month_header(ws, row, extra=()):
    labels = ["($K unless noted)"] + MONTHS + list(extra)
    header(ws, row, list(range(1, 1 + len(labels))), labels)


wb = Workbook()

# ==================================================================== README
ws = wb.active
ws.title = "README"
title(ws, "CVR Engineering — Phase 2 Forecast Model (Jul 2026 – Dec 2027)",
      "Generated by scripts/build_phase2_workbook.py. Companion to CVR_Model_Phase1_Baseline.xlsx.")
rows = [
    "",
    "WHAT THIS IS",
    "A driver-based re-forecast built from the Phase 1 baseline. It does NOT adopt the official 2026",
    "budget as the base case (H1 came in 46% under it); the budget appears as a comparison line instead.",
    "Every output shows three views: Actual (H1), Budget (official), Forecast (driver-based).",
    "",
    "HOW THE ENGINE WORKS",
    "  Revenue      = FTE × 173.33 hrs/mo × utilization × blended card rate × realization",
    "  Direct labor = FTE × avg wage/mo × direct-charge share (GL convention, ~92%)",
    "  Burden 33.8% of wages · other OpEx at H1 run rate · overhead $17,250/mo · interest on parent note",
    "  Cash: AR at DSO days of revenue; every operating dollar draws on / repays the USC parent note.",
    "",
    "TABS",
    "  Drivers            — scenario selector (1=Base 2=Upside 3=Downside) + scalar inputs (blue).",
    "  Scenario Paths     — the three monthly paths for FTE, utilization, realization. Edit to taste.",
    "  Forecast P&L       — monthly engine output with H2-2026 and FY-2027 subtotals.",
    "  Cash & Note        — AR, operating cash, and the parent-note roll-forward (funds every deficit).",
    "  Backlog & Pipeline — remaining value on active jobs + probability-weighted bids; coverage check.",
    "  FY Summary         — FY2026 landing (H1 actual + H2 forecast) vs budget; FY2027 vs the $6M goal.",
    "  Checks             — anchors to the GL baseline and internal integrity checks.",
    "  Coverage Chart     — native chart: forecast line vs backlog + pipeline areas, with a 1/0 toggle",
    "                       cell (B3) that includes or excludes the weighted pipeline live.",
    "",
    "COLOR KEY: blue = input · black = calculated · orange italics = assumption to confirm",
]
for i, text in enumerate(rows, start=3):
    c = ws.cell(row=i, column=1, value=text)
    if text in ("WHAT THIS IS", "HOW THE ENGINE WORKS", "TABS", "COLOR KEY: blue = input · black = calculated · orange italics = assumption to confirm"):
        c.font = F_SUB
widths(ws, {"A": 108})

# ============================================================ Scenario Paths
ws = wb.create_sheet("Scenario Paths")
title(ws, "Scenario Paths — monthly driver values",
      "Three preset paths per driver. The Drivers tab selector picks the active row. All cells editable (blue).")
header(ws, 4, list(range(1, 2 + NM)), ["Path"] + MONTHS)


def path_block(ws, r, label, paths, fmt):
    for k, (name, vals) in enumerate(paths):
        rr = r + k
        ws.cell(row=rr, column=1, value=f"{label} — {name}").font = F_SUB if k == 0 else None
        for j, v in enumerate(vals):
            c = ws.cell(row=rr, column=2 + j, value=v)
            c.number_format = fmt
            c.font = F_INPUT
            c.border = BOX
    return r + len(paths) + 1


r = 5
FTE_R0 = r
r = path_block(ws, r, "FTE", [("Base", BASE_FTE), ("Upside", UP_FTE), ("Downside", DN_FTE)], '0')
UTIL_R0 = r
r = path_block(ws, r, "Utilization", [("Base", BASE_UTIL), ("Upside", UP_UTIL), ("Downside", DN_UTIL)], PCT)
REAL_R0 = r
r = path_block(ws, r, "Realization", [("Base", BASE_REAL), ("Upside", UP_REAL), ("Downside", DN_REAL)], PCT)
ws.cell(row=r + 1, column=1,
        value=("Base: utilization 59%→70%, realization 79%→90%, 10→13 FTE. Upside: 75% / 95% / 16 FTE. "
               "Downside: no improvement, no hires. Hiring lead time and ramp are embedded in the FTE path — "
               "a hire contributes a full FTE the month shown.")).font = F_NOTE
widths(ws, {"A": 24})

# ==================================================================== Drivers
ws = wb.create_sheet("Drivers")
title(ws, "Drivers", "Selector + scalar inputs. Monthly driver rows pull from Scenario Paths via the selector.")
ws["A2"] = "Scenario selector (1=Base, 2=Upside, 3=Downside)"
sel = ws.cell(row=2, column=2, value=1)
sel.font = F_INPUT
sel.border = BOX
ws.cell(row=2, column=3, value='=CHOOSE(B2,"BASE","UPSIDE","DOWNSIDE")').font = F_SUB

month_header(ws, 5)
driver_rows = [("FTE (billable roster)", FTE_R0, '0.0'),
               ("Utilization", UTIL_R0, PCT),
               ("Realization", REAL_R0, PCT)]
for i, (label, block_r0, fmt) in enumerate(driver_rows):
    rr = 6 + i
    ws.cell(row=rr, column=1, value=label).font = F_SUB
    for j in range(NM):
        col = get_column_letter(2 + j)
        c = ws.cell(row=rr, column=2 + j,
                    value=f"=INDEX('Scenario Paths'!{col}{block_r0}:{col}{block_r0 + 2},$B$2)")
        c.number_format = fmt
        c.border = BOX
# scalar inputs
r = 11
header(ws, r, [1, 2, 3], ["Scalar input", "Value", "Source"])
r += 1
scalars = [
    ("Blended card rate ($/hr)", 154.47, '"$"#,##0.00', "Phase 1 Roster & Hours (mix-weighted)"),
    ("Avg loaded wage per FTE-month ($)", 7756, '#,##0', "GL H1: $465.4K wages ÷ 6 mo ÷ 10 FTE"),
    ("Direct-charge share of wages", 0.92, PCT, "GL H1: direct labor $428.5K of $465.4K total wages"),
    ("Burden % of wages", 0.338, PCT, "GL H1 burden lines ÷ wages"),
    ("Other OpEx per month ($)", 19193, '#,##0', "GL H1: OpEx less burden, overhead, indirect labor, ÷ 6"),
    ("Corporate overhead per month ($)", 17250, '#,##0', "GL: flat allocation"),
    ("Interest rate on parent note (APR)", 0.0175, '0.00%', "GL H1: $30.1K ÷ 6 ÷ $3.44M ×12"),
    ("DSO (days sales outstanding)", 46, '0', "GL: AR $139.8K vs H1 revenue"),
    ("Available hours per FTE-month", 173.33, '0.00', "2,080 ÷ 12"),
]
SCAL0 = r  # first scalar row
for name, val, fmt, src in scalars:
    ws.cell(row=r, column=1, value=name).border = BOX
    v = ws.cell(row=r, column=2, value=val)
    v.number_format = fmt
    v.font = F_INPUT
    v.border = BOX
    s = ws.cell(row=r, column=3, value=src)
    s.font = F_NOTE
    s.border = BOX
    r += 1
widths(ws, {"A": 36, "B": 12, "C": 60})
# scalar cell map
CARD = f"Drivers!$B${SCAL0}"
WAGE = f"Drivers!$B${SCAL0+1}"
DSHARE = f"Drivers!$B${SCAL0+2}"
BURDEN = f"Drivers!$B${SCAL0+3}"
OTHER = f"Drivers!$B${SCAL0+4}"
OVH = f"Drivers!$B${SCAL0+5}"
APR = f"Drivers!$B${SCAL0+6}"
DSO = f"Drivers!$B${SCAL0+7}"
HRS_MO = f"Drivers!$B${SCAL0+8}"
FTE_ROW, UTIL_ROW, REAL_ROW = 6, 7, 8

# =============================================================== Forecast P&L
ws = wb.create_sheet("Forecast P&L")
title(ws, "Forecast P&L — monthly, July 2026 – December 2027 (all figures $K)",
      "Driven entirely by the Drivers tab. Change the scenario selector or any blue input and this recomputes.")
month_header(ws, 4, extra=["H2-2026", "FY-2027"])


def frow(ws, r, label, per_col, fmt=KFMT, font=None, subtotal=True):
    lab = ws.cell(row=r, column=1, value=label)
    if font:
        lab.font = font
    for j in range(NM):
        col = get_column_letter(2 + j)
        c = ws.cell(row=r, column=2 + j, value=per_col(col))
        c.number_format = fmt
        c.border = BOX
    if subtotal:
        for cc, (a, b) in ((H2_COL, ("B", "G")), (FY27_COL, ("H", "S"))):
            c = ws.cell(row=r, column=cc, value=f"=SUM({a}{r}:{b}{r})")
            c.number_format = fmt
            c.border = BOX
            c.fill = FILL_TOT
    return r + 1


r = 5
BH = r
r = frow(ws, r, "Billable hours", lambda c: f"=Drivers!{c}${FTE_ROW}*{HRS_MO}*Drivers!{c}${UTIL_ROW}", fmt=HRS)
REV = r
r = frow(ws, r, "Revenue", lambda c: f"={c}{BH}*{CARD}*Drivers!{c}${REAL_ROW}/1000", font=F_SUB)
DL = r
r = frow(ws, r, "Direct labor", lambda c: f"=Drivers!{c}${FTE_ROW}*{WAGE}*{DSHARE}/1000")
GPR = r
r = frow(ws, r, "Gross Profit", lambda c: f"={c}{REV}-{c}{DL}", font=F_SUB)
lab = ws.cell(row=r, column=1, value="Gross margin %")
for j in range(NM):
    col = get_column_letter(2 + j)
    c = ws.cell(row=r, column=2 + j, value=f"={col}{GPR}/{col}{REV}")
    c.number_format = PCT
for cc in (H2_COL, FY27_COL):
    col = get_column_letter(cc)
    c = ws.cell(row=r, column=cc, value=f"={col}{GPR}/{col}{REV}")
    c.number_format = PCT
r += 1
IL = r
r = frow(ws, r, "Indirect labor", lambda c: f"=Drivers!{c}${FTE_ROW}*{WAGE}*(1-{DSHARE})/1000")
BU = r
r = frow(ws, r, "Burden (taxes, benefits, vac/hol)", lambda c: f"=Drivers!{c}${FTE_ROW}*{WAGE}*{BURDEN}/1000")
OO = r
r = frow(ws, r, "Other operating expenses", lambda c: f"={OTHER}/1000")
OV = r
r = frow(ws, r, "Corporate overhead allocation", lambda c: f"={OVH}/1000")
TOX = r
r = frow(ws, r, "Total Operating Expenses", lambda c: f"=SUM({c}{IL}:{c}{OV})", font=F_SUB)
OI = r
r = frow(ws, r, "Operating Income / (Loss)", lambda c: f"={c}{GPR}-{c}{TOX}", font=F_SUB)
INT = r
r = frow(ws, r, "Interest (parent note)", lambda c: f"='Cash & Note'!{c}6*{APR}/12")
NI = r
r = frow(ws, r, "Net Income / (Loss)", lambda c: f"={c}{OI}-{c}{INT}", font=F_SUB)
lab = ws.cell(row=r, column=1, value="OILI return % (OI − interest) ÷ revenue")
for j in range(NM):
    col = get_column_letter(2 + j)
    c = ws.cell(row=r, column=2 + j, value=f"=({col}{OI}-{col}{INT})/{col}{REV}")
    c.number_format = PCT
for cc in (H2_COL, FY27_COL):
    col = get_column_letter(cc)
    c = ws.cell(row=r, column=cc, value=f"=({col}{OI}-{col}{INT})/{col}{REV}")
    c.number_format = PCT
r += 2
ws.cell(row=r, column=1,
        value=("Direct labor follows the GL convention (~92% of wages charged to jobs), so gross margin here is "
               "comparable to the GL statements — improvement comes from revenue per FTE, not reclassification.")).font = F_NOTE
widths(ws, {"A": 34, **{get_column_letter(c): 9 for c in range(2, 2 + NM)},
            get_column_letter(H2_COL): 11, get_column_letter(FY27_COL): 11})
PL = {"rev": REV, "gp": GPR, "oi": OI, "int": INT, "ni": NI, "bh": BH}

# ================================================================ Cash & Note
ws = wb.create_sheet("Cash & Note")
title(ws, "Cash & Parent-Note Roll-Forward (all figures $K)",
      "CVR holds no cash: deficits draw on the USC parent note, surpluses repay it. Interest accrues on the opening balance.")
month_header(ws, 4)


def _cashrow(ws, r, label, per_col, fmt, font):
    lab = ws.cell(row=r, column=1, value=label)
    if font:
        lab.font = font
    for j in range(NM):
        col = get_column_letter(2 + j)
        c = ws.cell(row=r, column=2 + j, value=per_col(col, j))
        c.number_format = fmt
        c.border = BOX
    return r + 1


r = _cashrow(ws, 5, "Net Income / (Loss)", lambda c, j: f"='Forecast P&L'!{c}{PL['ni']}", KFMT, None)
r = _cashrow(ws, r, "Opening note balance",
             lambda c, j: (H1["note_open"] if j == 0 else f"={get_column_letter(1 + j)}10"), KFMT, None)
r = _cashrow(ws, r, "AR balance (DSO × revenue)",
             lambda c, j: f"='Forecast P&L'!{c}{PL['rev']}*{DSO}/30.4", KFMT, None)
r = _cashrow(ws, r, "Δ AR",
             lambda c, j: (f"={c}7-{H1['ar_open']}" if j == 0 else f"={c}7-{get_column_letter(1 + j)}7"), KFMT, None)
r = _cashrow(ws, r, "Operating cash flow", lambda c, j: f"={c}5-{c}8", KFMT, F_SUB)
r = _cashrow(ws, r, "Closing note balance", lambda c, j: f"={c}6-{c}9", KFMT, F_SUB)
ws.cell(row=r + 1, column=1,
        value=("Opening note balance 6/30/26: $3,436.6K. The official budget expects a $157.8K paydown by "
               "year-end; this tab shows what the driver-based forecast actually implies.")).font = F_NOTE
widths(ws, {"A": 30, **{get_column_letter(c): 9 for c in range(2, 2 + NM)}})

# ========================================================= Backlog & Pipeline
ws = wb.create_sheet("Backlog & Pipeline")
title(ws, "Backlog, Pipeline, and Forecast Coverage (all figures $K)",
      "Backlog = remaining PO value on active jobs (KPI scorecard 7/11/26). Pipeline = pending bids × win probability.")
header(ws, 4, list(range(1, 8)), ["Job", "Customer / name", "PO value", "Billed to date", "Remaining", "Sched. finish", "Note"])
BACKLOG = [
    ("001-0001", "DTE — Catalina Conversion Ph 3", 838.451, 806.331, "2026", "construction support tail"),
    ("001-0003", "DTE — New Baltimore Conversion", 1428.796, 1216.312, "Dec-27", "64% complete"),
    ("005-0004", "Consumers — 2026 HVD Line Sensors", 130.493, 71.268, "Oct-26", "77% complete"),
    ("016-0001", "Cloverland — Manistique Pump Stn", 111.510, 106.628, "Sep-26", "99% — cost overrun job"),
    ("017-0003", "CenterPoint — Gateway 69kV", 203.015, 131.230, "Aug-26", "65% complete"),
    ("017-0004", "CenterPoint — Rockport 69kV", 96.712, 81.692, "Aug-26", "88% complete"),
    ("017-0005", "CenterPoint — Angel Mounds 69kV", 96.987, 95.148, "Oct-26", "88% complete"),
    ("017-0006", "CenterPoint — Northwest 69kV", 110.555, 4.365, "Aug-27", "13% — early"),
    ("017-0007", "CenterPoint — Leonard Rd 69kV", 199.994, 6.739, "Oct-27", "17% — early"),
]
r0 = 5
for i, (job, name, po, billed, fin, note) in enumerate(BACKLOG):
    r = r0 + i
    ws.cell(row=r, column=1, value=job).border = BOX
    ws.cell(row=r, column=2, value=name).border = BOX
    for col, v in ((3, po), (4, billed)):
        c = ws.cell(row=r, column=col, value=v)
        c.number_format = KFMT
        c.border = BOX
    c = ws.cell(row=r, column=5, value=f"=C{r}-D{r}")
    c.number_format = KFMT
    c.border = BOX
    ws.cell(row=r, column=6, value=fin).border = BOX
    n = ws.cell(row=r, column=7, value=note)
    n.font = F_NOTE
    n.border = BOX
BK_TOT = r0 + len(BACKLOG)
ws.cell(row=BK_TOT, column=2, value="Total backlog remaining").font = F_SUB
c = ws.cell(row=BK_TOT, column=5, value=f"=SUM(E{r0}:E{BK_TOT-1})")
c.number_format = KFMT
c.font = F_SUB
c.fill = FILL_TOT
r = BK_TOT + 2
ws.cell(row=r, column=1, value="PIPELINE — pending bids (CVR scope)").font = F_SUB
r += 1
header(ws, r, list(range(1, 7)), ["Bid", "Customer", "CVR value", "Win prob.", "Expected", "Expected award"])
r += 1
PIPE = [
    ("Frontier Make Ready", "Steuben County REMC", 100.0, 0.50, "Q3-26"),
    ("Jacksonburg–Gateway (EPC-paired $3.55M)", "Hoosier Energy", 160.0, 0.50, "Q4-26"),
    ("Rosehill–Rockport (EPC-paired $5.59M)", "Hoosier Energy", 290.0, 0.50, "Q4-26"),
    ("Joint Use Audit", "Lansing Board of Water & Light", 1350.0, 0.50, "Q4-26"),
    ("2026 Pole Replacements (EPC-paired $3.45M)", "Consumers Energy", 276.0, 0.67, "Q4-26"),
    ("Renaissance 345kV Substation (ON HOLD)", "DTE Energy", 0.0, 0.00, "hold"),
]
p0 = r
for i, (bid, cust, val, prob, when) in enumerate(PIPE):
    r = p0 + i
    ws.cell(row=r, column=1, value=bid).border = BOX
    ws.cell(row=r, column=2, value=cust).border = BOX
    c = ws.cell(row=r, column=3, value=val)
    c.number_format = KFMT
    c.border = BOX
    pr = ws.cell(row=r, column=4, value=prob)
    pr.number_format = PCT
    pr.font = F_INPUT
    pr.border = BOX
    c = ws.cell(row=r, column=5, value=f"=C{r}*D{r}")
    c.number_format = KFMT
    c.border = BOX
    ws.cell(row=r, column=6, value=when).border = BOX
PIPE_TOT = p0 + len(PIPE)
ws.cell(row=PIPE_TOT, column=2, value="Total probability-weighted pipeline").font = F_SUB
c = ws.cell(row=PIPE_TOT, column=5, value=f"=SUM(E{p0}:E{PIPE_TOT-1})")
c.number_format = KFMT
c.font = F_SUB
c.fill = FILL_TOT
r = PIPE_TOT + 2
ws.cell(row=r, column=1, value="COVERAGE CHECK").font = F_SUB
r += 1
cov = [
    ("Forecast revenue, Jul-26 – Dec-27", f"='Forecast P&L'!{get_column_letter(H2_COL)}{PL['rev']}+'Forecast P&L'!{get_column_letter(FY27_COL)}{PL['rev']}"),
    ("Booked + expected work (backlog + weighted pipeline)", f"=E{BK_TOT}+E{PIPE_TOT}"),
    ("Coverage ratio", None),
]
cov0 = r
for label, formula in cov:
    ws.cell(row=r, column=1, value=label).border = BOX
    c = ws.cell(row=r, column=2, value=formula if formula else f"=B{r-1}/B{r-2}")
    c.number_format = KFMT if formula else PCT
    c.border = BOX
    r += 1
ws.cell(row=r + 1, column=1,
        value=("Coverage below 100% is normal at an 18-month horizon — the gap is work still to be won. But if "
               "coverage falls much below ~60%, the forecast is leaning on unidentified sales; treat the gap as "
               "the BD target: it quantifies how much new work Estimating must originate beyond the current bid list.")).font = F_NOTE
widths(ws, {"A": 40, "B": 34, "C": 12, "D": 12, "E": 12, "F": 13, "G": 24})
COV_FC_ROW, COV_BOOK_ROW = cov0, cov0 + 1

# ================================================================= FY Summary
ws = wb.create_sheet("FY Summary")
title(ws, "Fiscal-Year Summary — Actual · Budget · Forecast (all figures $K)",
      "FY2026 = H1 actual (GL) + H2 forecast. FY2027 = forecast vs the $6M Year-2 divisional goal.")
header(ws, 4, [1, 2, 3, 4, 5, 6], ["FY2026", "H1 Actual", "H2 Forecast", "FY Total", "Official Budget", "FY vs Budget"])
T = get_column_letter(H2_COL)
U = get_column_letter(FY27_COL)
fy_rows = [
    ("Revenue", H1["rev"], f"='Forecast P&L'!{T}{PL['rev']}", BUDGET_FY26["rev"]),
    ("Gross Profit", H1["gp"], f"='Forecast P&L'!{T}{PL['gp']}", BUDGET_FY26["gp"]),
    ("Operating Income / (Loss)", H1["oi"], f"='Forecast P&L'!{T}{PL['oi']}", BUDGET_FY26["ni"]),
    ("Interest", H1["int"], f"='Forecast P&L'!{T}{PL['int']}", 0.0),
    ("Net Income / (Loss)", H1["ni"], f"='Forecast P&L'!{T}{PL['ni']}", BUDGET_FY26["ni"]),
]
r = 5
FY26_0 = r
for label, h1, fc, bud in fy_rows:
    ws.cell(row=r, column=1, value=label).border = BOX
    a = ws.cell(row=r, column=2, value=h1)
    f = ws.cell(row=r, column=3, value=fc)
    t = ws.cell(row=r, column=4, value=f"=B{r}+C{r}")
    b = ws.cell(row=r, column=5, value=bud)
    d = ws.cell(row=r, column=6, value=f"=D{r}-E{r}")
    for cell in (a, f, t, b, d):
        cell.number_format = KFMT
        cell.border = BOX
    t.font = F_SUB
    r += 1
ws.cell(row=r, column=1, value="OILI return % (FY)").border = BOX
c = ws.cell(row=r, column=2, value=f"=(D{FY26_0+2}-D{FY26_0+3})/D{FY26_0}")
c.number_format = PCT
r += 1
ws.cell(row=r, column=1, value="Note balance at 12/31/26").border = BOX
c = ws.cell(row=r, column=2, value="='Cash & Note'!G10")
c.number_format = KFMT
r += 2
header(ws, r, [1, 2, 3, 4], ["FY2027", "Forecast", "Year-2 Goal", "% of goal"])
r += 1
FY27_0 = r
fy27 = [
    ("Revenue", f"='Forecast P&L'!{U}{PL['rev']}", 6000.0),
    ("Gross Profit", f"='Forecast P&L'!{U}{PL['gp']}", None),
    ("Operating Income / (Loss)", f"='Forecast P&L'!{U}{PL['oi']}", None),
    ("Net Income / (Loss)", f"='Forecast P&L'!{U}{PL['ni']}", None),
]
for label, fc, goal in fy27:
    ws.cell(row=r, column=1, value=label).border = BOX
    f = ws.cell(row=r, column=2, value=fc)
    f.number_format = KFMT
    f.border = BOX
    if goal is not None:
        g = ws.cell(row=r, column=3, value=goal)
        g.number_format = KFMT
        g.border = BOX
        p = ws.cell(row=r, column=4, value=f"=B{r}/C{r}")
        p.number_format = PCT
        p.border = BOX
    r += 1
ws.cell(row=r, column=1, value="OILI return % (FY27)").border = BOX
c = ws.cell(row=r, column=2,
            value=f"=('Forecast P&L'!{U}{PL['oi']}-'Forecast P&L'!{U}{PL['int']})/'Forecast P&L'!{U}{PL['rev']}")
c.number_format = PCT
r += 1
ws.cell(row=r, column=1, value="Note balance at 12/31/27").border = BOX
c = ws.cell(row=r, column=2, value="='Cash & Note'!S10")
c.number_format = KFMT
r += 2
ws.cell(row=r, column=1,
        value=("The gap between FY27 forecast revenue and the $6M goal is structural (billable capacity), not "
               "effort: closing it requires the hiring ramp AND winning EPC-paired engineering at scale — see the "
               "utilization × realization grid in the Phase 1 workbook for the per-FTE ceiling math.")).font = F_NOTE
widths(ws, {"A": 28, "B": 13, "C": 14, "D": 12, "E": 14, "F": 13})

# ====================================================================== Checks
ws = wb.create_sheet("Checks")
title(ws, "Integrity checks")
header(ws, 4, [1, 2, 3, 4], ["Check", "Model", "Expected", "Status"])
checks = [
    ("H1 revenue anchor ($K)", "='FY Summary'!B5", 551.0, 0.5),
    ("H1 net income anchor ($K)", "='FY Summary'!B9", -320.5, 0.5),
    ("Backlog remaining total ($K)", f"='Backlog & Pipeline'!E{BK_TOT}", 696.8, 2.0),
    ("Note roll integrity: Dec-27 close = open − Σ op cash",
     "='Cash & Note'!S10", None, None),
    ("Coverage ratio computed", f"='Backlog & Pipeline'!B{COV_BOOK_ROW}", None, None),
]
r = 5
for label, formula, target, tol in checks:
    ws.cell(row=r, column=1, value=label).border = BOX
    m = ws.cell(row=r, column=2, value=formula)
    m.number_format = KFMT
    m.border = BOX
    if target is not None:
        t = ws.cell(row=r, column=3, value=target)
        t.number_format = KFMT
        t.border = BOX
        s = ws.cell(row=r, column=4, value=f'=IF(ABS(B{r}-C{r})<={tol},"TIES","CHECK")')
        s.border = BOX
    elif "Note roll" in label:
        t = ws.cell(row=r, column=3, value=f"={H1['note_open']}-SUM('Cash & Note'!B9:S9)")
        t.number_format = KFMT
        t.border = BOX
        s = ws.cell(row=r, column=4, value=f'=IF(ABS(B{r}-C{r})<=0.1,"TIES","CHECK")')
        s.border = BOX
    else:
        ws.cell(row=r, column=3, value=">0 expected").font = F_NOTE
        s = ws.cell(row=r, column=4, value=f'=IF(B{r}>0,"OK","CHECK")')
        s.border = BOX
    r += 1
r += 1
ws.cell(row=r, column=1, value="MODEL LIMITS (read before presenting)").font = F_SUB
r += 1
for item in [
    "Revenue is capacity-driven; the coverage check disciplines it against booked work, but it is not a job-by-job burn schedule.",
    "Direct-charge share (92%) mirrors the GL convention; when salary detail arrives, split wages properly by person.",
    "The FTE path assumes hires are productive in month one — add ramp months per hire if that proves optimistic.",
    "Pipeline probabilities are placeholders at the 2026 win rate (67%) or 50% — Estimating should own these numbers.",
    "Escalation is off (card rate and wages flat through 2027) — turn on via the scalar inputs when the 2027 rate sheet lands.",
]:
    ws.cell(row=r, column=1, value="• " + item)
    r += 1
widths(ws, {"A": 66, "B": 14, "C": 14, "D": 10})

# ============================================================= Coverage Chart
from openpyxl.chart import AreaChart, LineChart, Reference
from openpyxl.drawing.line import LineProperties

BLUE, AREA1, AREA2 = "2A78D6", "9EC5F4", "CDE2FB"

ws = wb.create_sheet("Coverage Chart")
title(ws, "Forecast & work coverage — with pipeline toggle",
      "Native chart wired to live cells. Set the toggle to 0 to see booked backlog only; edit job remainders or bid probabilities and everything redraws.")

ws.cell(row=3, column=1, value="Include weighted pipeline? (1 = yes, 0 = no)").font = F_SUB
tog = ws.cell(row=3, column=2, value=1)
tog.font = F_INPUT
tog.border = BOX
TOG = "$B$3"

DATA0 = 24  # data block start row
ws.cell(row=DATA0 - 1, column=1, value="CHART DATA ($K/month) — formulas reference Backlog & Pipeline and Forecast P&L").font = F_SUB
ws.cell(row=DATA0, column=1, value="Month")
for j, m in enumerate(MONTHS):
    ws.cell(row=DATA0, column=2 + j, value=m)

# per-job burn rows (even spread Jul-26 .. finish); ends = month index of last burn
JOB_ENDS = [5, 17, 3, 2, 1, 1, 3, 13, 15]  # matches BACKLOG order rows 5..13
for k, end in enumerate(JOB_ENDS):
    r = DATA0 + 1 + k
    ws.cell(row=r, column=1, value="burn: " + BACKLOG[k][1]).font = F_NOTE
    for j in range(NM):
        ws.cell(row=r, column=2 + j,
                value=(f"='Backlog & Pipeline'!$E{5 + k}/{end + 1}" if j <= end else 0))
BK_ROW = DATA0 + 1 + len(JOB_ENDS)
ws.cell(row=BK_ROW, column=1, value="Booked backlog").font = F_SUB
for j in range(NM):
    col = get_column_letter(2 + j)
    ws.cell(row=BK_ROW, column=2 + j, value=f"=SUM({col}{DATA0 + 1}:{col}{BK_ROW - 1})")

# per-bid rows: value x prob / duration, from award start
BID_SCHED = [(2, 6), (4, 12), (4, 12), (5, 18), (4, 12)]  # (start idx, months) rows 18..22
for k, (s, dur) in enumerate(BID_SCHED):
    r = BK_ROW + 1 + k
    ws.cell(row=r, column=1, value="bid: " + PIPE[k][0][:34]).font = F_NOTE
    for j in range(NM):
        ws.cell(row=r, column=2 + j,
                value=(f"='Backlog & Pipeline'!$C{18 + k}*'Backlog & Pipeline'!$D{18 + k}/{dur}"
                       if s <= j < s + dur else 0))
PIPE_ROW = BK_ROW + 1 + len(BID_SCHED)
ws.cell(row=PIPE_ROW, column=1, value="Weighted pipeline (× toggle)").font = F_SUB
for j in range(NM):
    col = get_column_letter(2 + j)
    ws.cell(row=PIPE_ROW, column=2 + j,
            value=f"=SUM({col}{BK_ROW + 1}:{col}{PIPE_ROW - 1})*{TOG}")
FC_ROW = PIPE_ROW + 1
ws.cell(row=FC_ROW, column=1, value="Forecast revenue").font = F_SUB
for j in range(NM):
    col = get_column_letter(2 + j)
    ws.cell(row=FC_ROW, column=2 + j, value=f"='Forecast P&L'!{col}{PL['rev']}")

ws.cell(row=5, column=1, value="Coverage of forecast")
cov = ws.cell(row=5, column=2,
              value=f"=(SUM(B{BK_ROW}:S{BK_ROW})+SUM(B{PIPE_ROW}:S{PIPE_ROW}))/SUM(B{FC_ROW}:S{FC_ROW})")
cov.number_format = PCT
cov.font = F_SUB
ws.cell(row=6, column=1, value="Gap to originate ($K)")
gap = ws.cell(row=6, column=2,
              value=f"=SUM(B{FC_ROW}:S{FC_ROW})-SUM(B{BK_ROW}:S{BK_ROW})-SUM(B{PIPE_ROW}:S{PIPE_ROW})")
gap.number_format = KFMT
gap.font = F_SUB

cats = Reference(ws, min_col=2, max_col=1 + NM, min_row=DATA0)
area = AreaChart(grouping="stacked")
area.title = "Forecast revenue vs booked backlog + weighted pipeline ($K/month)"
area.height, area.width = 10, 24
area.add_data(Reference(ws, min_col=1, max_col=1 + NM, min_row=BK_ROW), titles_from_data=True, from_rows=True)
area.add_data(Reference(ws, min_col=1, max_col=1 + NM, min_row=PIPE_ROW), titles_from_data=True, from_rows=True)
area.set_categories(cats)
area.series[0].graphicalProperties.solidFill = AREA1
area.series[1].graphicalProperties.solidFill = AREA2
area.y_axis.title = "$K per month"
area.y_axis.scaling.min, area.y_axis.scaling.max = 0, 250
ln = LineChart()
ln.add_data(Reference(ws, min_col=1, max_col=1 + NM, min_row=FC_ROW), titles_from_data=True, from_rows=True)
ln.set_categories(cats)
ln.series[0].graphicalProperties.line = LineProperties(solidFill=BLUE, w=28000)
ln.series[0].smooth = False
ln.y_axis.axId = 200
ln.y_axis.scaling.min, ln.y_axis.scaling.max = 0, 250
ln.y_axis.delete = True
area += ln
ws.add_chart(area, "A8")
widths(ws, {"A": 40})

os.makedirs("model", exist_ok=True)
out = "model/CVR_Model_Phase2_Forecast.xlsx"
wb.save(out)
print(f"wrote {out}")
