#!/usr/bin/env python3
"""Build the CVR Engineering Phase 1 baseline workbook.

Sources (see data/):
  - CVR_Rate_Sheet_2026.pdf                  -> Rates tab
  - CVR_EPC_KPI_2026-07-11.pdf               -> Roster hours, Jan-May monthlies, EPC, checks
  - CVR_Financial_Statements_2026-06-30.pdf  -> GL income statement detail, balance sheet,
                                                cash flow, sales by customer (June + YTD)

The KPI report published Revenue / GP / Net Income monthly through May; the GL
statements add June and full line-item detail. The two sources cross-tie
(checks tab) : GL YTD-June minus GL June equals the KPI Jan-May figures.

Output: model/CVR_Model_Phase1_Baseline.xlsx
"""

import os

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

# ---------------------------------------------------------------- styling ---
NAVY = "1F3864"
LIGHT = "D9E2F3"
INPUT_BLUE = "0070C0"
FLAG_ORANGE = "C55A11"
GREY = "F2F2F2"

F_TITLE = Font(bold=True, size=14, color=NAVY)
F_H = Font(bold=True, color="FFFFFF")
F_SUB = Font(bold=True, color=NAVY)
F_INPUT = Font(color=INPUT_BLUE)
F_FLAG = Font(color=FLAG_ORANGE, italic=True)
F_NOTE = Font(italic=True, size=9, color="595959")
FILL_H = PatternFill("solid", fgColor=NAVY)
FILL_TOT = PatternFill("solid", fgColor=GREY)
THIN = Side(style="thin", color="BFBFBF")
BOX = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

USD = '"$"#,##0.00'
D0 = '#,##0;(#,##0)'
KFMT = '#,##0.0;(#,##0.0)'
HRS = '#,##0.0'
PCT = '0.0%'


def header(ws, row, cols, labels):
    for c, label in zip(cols, labels):
        cell = ws.cell(row=row, column=c, value=label)
        cell.font = F_H
        cell.fill = FILL_H
        cell.alignment = Alignment(horizontal="center", wrap_text=True)
        cell.border = BOX


def title(ws, text, sub=None):
    ws["A1"] = text
    ws["A1"].font = F_TITLE
    if sub:
        ws["A2"] = sub
        ws["A2"].font = F_NOTE


def widths(ws, spec):
    for col, w in spec.items():
        ws.column_dimensions[col].width = w


wb = Workbook()

# ==================================================================== README
ws = wb.active
ws.title = "README"
title(ws, "CVR Engineering — Phase 1 Baseline Model",
      "v2: GL financial statements through 6/30/2026 incorporated. Generated by scripts/build_phase1_workbook.py.")
rows = [
    "",
    "PURPOSE",
    "Phase 1 of the financial model build: a quantified current-state baseline reconciled to the",
    "KPI report (7/11/2026), the 2026 rate sheet, and the GL financial statements through 6/30/2026.",
    "",
    "TABS",
    "  Assumptions          — global inputs (blue). Overhead, interest, and burden now sourced from GL.",
    "  Rates                — 2026 rate sheet, effective January 2026.",
    "  Roster & Hours       — people, classifications, YTD hours and utilization vs target, value at card rates.",
    "  Labor Cost           — per-person standard cost rates (COINS timesheet report), loaded cost, and margin by role.",
    "  Baseline P&L         — CVR monthly actuals vs budget, Jan–Jun 2026 (Jan–May per KPI report, June per GL).",
    "  GL Income Stmt       — full line-item income statement, June and YTD, actual vs budget vs prior year.",
    "  Balance Sheet        — 6/30/2026 vs one year ago vs annual budget.",
    "  Cash Flow & Customers— six-month cash flow summary and sales by customer (incl. intercompany).",
    "  HWC EPC Baseline     — EPC line financials for context.",
    "  Realization          — the $/hr and labor-multiplier gap analysis plus the utilization × realization grid.",
    "  Checks & Open Items  — tie-outs across all three sources and remaining open questions.",
    "  Charts               — native charts wired to the data tabs (revenue vs plan/PY, gross margin,",
    "                         utilization vs target, sales by customer). Edit data; charts redraw.",
    "",
    "COLOR KEY",
    "  Blue  = input / assumption you can change",
    "  Black = calculated or sourced from a document",
    "  Orange italics = assumption that needs confirmation",
    "",
    "SOURCES",
    "  data/CVR_Rate_Sheet_2026.pdf",
    "  data/CVR_EPC_KPI_2026-07-11.pdf",
    "  data/CVR_Financial_Statements_2026-06-30.pdf",
    "  data/CVR_Timesheet_Costs_Jul2026_JC016755.pdf",
]
for i, text in enumerate(rows, start=3):
    c = ws.cell(row=i, column=1, value=text)
    if text in ("PURPOSE", "TABS", "COLOR KEY", "SOURCES"):
        c.font = F_SUB
widths(ws, {"A": 110})

# ================================================================ Assumptions
ws = wb.create_sheet("Assumptions")
title(ws, "Global Assumptions", "Blue cells are inputs. GL-sourced values are black.")
header(ws, 4, [1, 2, 3], ["Assumption", "Value", "Notes"])
assumptions = [
    ("Standard hours per FTE-year", 2080, '#,##0', True,
     "40 hrs x 52 wks; adjust for PTO/holiday policy if preferred"),
    ("Median target billable utilization", 0.75, PCT, True,
     "KPI report gauge target (median of per-person targets)"),
    ("Active billable headcount (current)", 10, '#,##0', True,
     "People with recorded hours in the KPI report"),
    ("Hours-to-June-30 adjustment factor", 0.949, '0.000', True,
     "KPI hours run through 7/11 (~27.4 wks); scales to Jan–Jun (26 wks) to match the GL period"),
    ("Employment burden load (computed from GL)", 0.338, PCT, False,
     "YTD burden (FICA, UI, WC, health, pension, benefits, vac/hol = $157.4K) ÷ total wages ($465.4K); refine with salary detail"),
    ("Corporate overhead allocation ($/month)", 17250, D0, False,
     "GL actual — flat monthly, matches budget ($103,500 YTD)"),
    ("Interest expense ($/month avg)", 5015, D0, False,
     "GL: $30,087 YTD ÷ 6, on Note Payable-Parent of $3.44M (not in budget)"),
    ("Year-2 divisional sales goal ($K)", 6000, '#,##0', True,
     "Divisional business target"),
    ("Year-2 OILI return target", 0.20, PCT, True,
     "OILI / revenue"),
]
r = 5
for name, val, fmt, is_input, note in assumptions:
    ws.cell(row=r, column=1, value=name).border = BOX
    v = ws.cell(row=r, column=2, value=val)
    v.border = BOX
    v.number_format = fmt
    if is_input:
        v.font = F_INPUT
    n = ws.cell(row=r, column=3, value=note)
    n.border = BOX
    n.font = F_NOTE
    r += 1
widths(ws, {"A": 42, "B": 14, "C": 90})
# cell map: B5 hrs/yr, B6 target util, B7 headcount, B8 hours factor,
#           B9 burden, B10 overhead/mo, B11 interest/mo, B12 goal, B13 OILI target

# ====================================================================== Rates
ws = wb.create_sheet("Rates")
title(ws, "CVR Engineering — Hourly Rates and Charges",
      "Effective January 2026. Source: data/CVR_Rate_Sheet_2026.pdf")
header(ws, 4, [1, 2], ["Classification", "Rate / hr"])
RATES = [
    ("Administrative Assistant", 59.62),
    ("Graphics Technician", 76.14),
    ("Project Manager", 159.86),
    ("Designer I", 79.91),
    ("Designer II", 95.70),
    ("Senior Designer", 105.01),
    ("Engineer I", 112.27),
    ("Engineer II", 138.09),
    ("Engineer III", 152.21),
    ("Engineer IV", 172.37),
    ("Senior Engineer", 241.57),
    ("Principal Engineer", 360.72),
]
r = 5
for name, rate in RATES:
    ws.cell(row=r, column=1, value=name).border = BOX
    c = ws.cell(row=r, column=2, value=rate)
    c.number_format = USD
    c.border = BOX
    r += 1
notes = [
    "Travel time in the interest of the work billed at full rates.",
    "No overtime multipliers — excess hours billed at standard rates.",
    "Mileage at IRS rate; ground/air travel and living expenses at cost.",
    "Purchases, out-of-scope subcontract work and other expenses at cost + 10%.",
]
r += 1
for note in notes:
    ws.cell(row=r, column=1, value="• " + note).font = F_NOTE
    r += 1
widths(ws, {"A": 30, "B": 12})
RATE_ROWS = {name: i + 5 for i, (name, _) in enumerate(RATES)}

# ============================================================ Roster & Hours
ws = wb.create_sheet("Roster & Hours")
title(ws, "Roster, YTD Hours and Utilization (2026 through week ending 7/11)",
      "Hours and splits from the KPI report utilization page. Orange classifications are assumptions pending confirmation.")
cols = list(range(1, 13))
header(ws, 4, cols, [
    "Name", "Billing classification", "Class source", "Rate / hr",
    "Total hrs YTD", "Billable %", "Non-billable %", "Bids %",
    "Billable hrs", "Target util %", "Util vs target", "Billable value @ card",
])
ROSTER = [
    ("Craig Peterson",   "Engineer I",          "org chart",              1017.00, 0.796, 0.204, 0.000, 0.754),
    ("Bhkti Patel",      "Engineer III",        "org chart",              1045.00, 0.744, 0.202, 0.055, 0.707),
    ("Taylor Nelson",    "Engineer II",         "ASSUMED — confirm",      1045.00, 0.610, 0.337, 0.054, 0.801),
    ("Hayley Worthen",   "Senior Engineer",     "org chart",               952.00, 0.669, 0.162, 0.169, 0.613),
    ("Francis Wagner",   "Engineer III",        "org chart",               992.00, 0.625, 0.343, 0.032, 0.707),
    ("Collin Allen",     "Graphics Technician", "org chart",               985.25, 0.576, 0.424, 0.000, 0.801),
    ("Kevin Metts",      "Designer II",         "ASSUMED — confirm",       890.00, 0.384, 0.598, 0.018, 0.754),
    ("Roy Pierce",       "Principal Engineer",  "ASSUMED billing class",   847.00, 0.327, 0.591, 0.082, 0.424),
    ("Randy Pynenberg",  "Engineer IV",         "org chart",                68.00, 0.897, 0.000, 0.103, 0.950),
    ("Auston Hopson",    "Graphics Technician", "org chart",                18.00, 1.000, 0.000, 0.000, 1.000),
    ("Tom Little",       "Engineer IV",         "org chart — no hours in KPI report", None, None, None, None, None),
    ("Erin Bryden",      "Engineer IV",         "org chart — no hours in KPI report", None, None, None, None, None),
    ("Patrick Nicholson","Senior Designer",     "org chart — no hours in KPI report", None, None, None, None, None),
]
r0 = 5
for i, (name, cls, src, hrs, bil, non, bid, tgt) in enumerate(ROSTER):
    r = r0 + i
    ws.cell(row=r, column=1, value=name).border = BOX
    c2 = ws.cell(row=r, column=2, value=cls)
    c2.border = BOX
    src_cell = ws.cell(row=r, column=3, value=src)
    src_cell.border = BOX
    src_cell.font = F_FLAG if "ASSUMED" in src or "no hours" in src else F_NOTE
    if "ASSUMED" in src:
        c2.font = F_FLAG
    rate_cell = ws.cell(row=r, column=4, value=f"=Rates!B{RATE_ROWS[cls]}")
    rate_cell.number_format = USD
    rate_cell.border = BOX
    for col, val, fmt in [(5, hrs, HRS), (6, bil, PCT), (7, non, PCT), (8, bid, PCT)]:
        c = ws.cell(row=r, column=col, value=val)
        c.number_format = fmt
        c.border = BOX
    bh = ws.cell(row=r, column=9, value=(f"=E{r}*F{r}" if hrs is not None else None))
    bh.number_format = HRS
    bh.border = BOX
    tg = ws.cell(row=r, column=10, value=tgt)
    tg.number_format = PCT
    tg.border = BOX
    var = ws.cell(row=r, column=11, value=(f"=F{r}-J{r}" if hrs is not None else None))
    var.number_format = PCT
    var.border = BOX
    val_c = ws.cell(row=r, column=12, value=(f"=I{r}*D{r}" if hrs is not None else None))
    val_c.number_format = '"$"#,##0'
    val_c.border = BOX
rt = r0 + len(ROSTER)
ws.cell(row=rt, column=1, value="TOTAL / blended").font = F_SUB
for col, fmt in [(5, HRS), (9, HRS), (12, '"$"#,##0')]:
    letter = get_column_letter(col)
    c = ws.cell(row=rt, column=col, value=f"=SUM({letter}{r0}:{letter}{rt-1})")
    c.number_format = fmt
    c.font = F_SUB
b = ws.cell(row=rt, column=4, value=f"=L{rt}/I{rt}")
b.number_format = USD
b.font = F_SUB
for col in range(1, 13):
    ws.cell(row=rt, column=col).fill = FILL_TOT
    ws.cell(row=rt, column=col).border = BOX
ws.cell(row=rt + 2, column=1,
        value=("KPI report totals: 8,052.25 total hrs · 4,747 billable · 2,896 non-billable · 405 bids · 59.0% total "
               "billable utilization. Roster above sums slightly lower (~193 hrs unattributed on the report page).")).font = F_NOTE
widths(ws, {"A": 18, "B": 20, "C": 30, "D": 11, "E": 12, "F": 11, "G": 13, "H": 9, "I": 12, "J": 12, "K": 12, "L": 16})
ROSTER_TOTAL_ROW = rt

# ================================================================= Labor Cost
# Per-person standard labor cost rates from the COINS Job Status - Timesheet
# Costs Report (JC016755), July 2026. Rates are consistent to the penny across
# every timesheet line, so they are COINS standard cost rates, not raw actuals.
# Assessed as base/pay rates (burden-exclusive) — see notes on the tab.
COST_RATES = {
    "Roy Pierce": 149.57,
    "Hayley Worthen": 138.05,
    "Bhkti Patel": 107.60,
    "Francis Wagner": 107.60,
    "Kevin Metts": 92.39,
    "Craig Peterson": 77.16,
    "Taylor Nelson": 77.16,
    "Collin Allen": 51.11,
    # not present on the pages captured — to confirm from a full report:
    "Randy Pynenberg": None,
    "Auston Hopson": None,
    "Tom Little": None,
    "Erin Bryden": None,
    "Patrick Nicholson": None,
}
ws = wb.create_sheet("Labor Cost")
title(ws, "Labor Cost — standard rates and margin by person",
      "Cost rates from COINS Timesheet Costs Report (JC016755), Jul 2026. Loaded cost = raw × (1 + burden). Burden on Assumptions.")
cols = list(range(1, 9))
header(ws, 4, cols, [
    "Name", "Billing classification", "Bill rate / hr", "Raw cost / hr",
    "Loaded cost / hr", "Margin / hr (bill − loaded)", "Cost multiplier (bill ÷ loaded)", "Billable value @ card"])
lc0 = 5
order = ["Roy Pierce", "Hayley Worthen", "Bhkti Patel", "Francis Wagner", "Kevin Metts",
         "Craig Peterson", "Taylor Nelson", "Collin Allen", "Randy Pynenberg", "Auston Hopson"]
cls_by_name = {name: cls for name, cls, *rest in ROSTER}
roster_row_by_name = {name: r0 + i for i, (name, *rest) in enumerate(ROSTER)}
for i, name in enumerate(order):
    r = lc0 + i
    cls = cls_by_name[name]
    ws.cell(row=r, column=1, value=name).border = BOX
    ws.cell(row=r, column=2, value=cls).border = BOX
    rate_cell = ws.cell(row=r, column=3, value=f"=Rates!B{RATE_ROWS[cls]}")
    rate_cell.number_format = USD
    rate_cell.border = BOX
    raw = COST_RATES.get(name)
    rc = ws.cell(row=r, column=4, value=raw)
    rc.number_format = USD
    rc.border = BOX
    if raw is None:
        rc.value = "TBD"
        rc.font = F_FLAG
    # loaded = raw * (1 + burden)  [Assumptions burden lives at B9]
    lc = ws.cell(row=r, column=5, value=(f"=D{r}*(1+Assumptions!$B$9)" if raw is not None else None))
    lc.number_format = USD
    lc.border = BOX
    mg = ws.cell(row=r, column=6, value=(f"=C{r}-E{r}" if raw is not None else None))
    mg.number_format = USD
    mg.border = BOX
    mult = ws.cell(row=r, column=7, value=(f"=C{r}/E{r}" if raw is not None else None))
    mult.number_format = '0.00"x"'
    mult.border = BOX
    # billable value at card, pulled from Roster & Hours col L
    rr = roster_row_by_name[name]
    bv = ws.cell(row=r, column=8, value=f"='Roster & Hours'!L{rr}")
    bv.number_format = '"$"#,##0'
    bv.border = BOX
lct = lc0 + len(order)
ws.cell(row=lct, column=1, value="Blended (weighted by billable hrs)").font = F_SUB
# weighted blended raw & loaded cost across people with known rates and hours
bl_raw = ws.cell(row=lct, column=4,
                 value=(f"=SUMPRODUCT('Roster & Hours'!I{r0}:I{r0+7},D{lc0}:D{lc0+7})/"
                        f"SUM('Roster & Hours'!I{r0}:I{r0+7})"))
bl_raw.number_format = USD
bl_raw.font = F_SUB
bl_load = ws.cell(row=lct, column=5, value=f"=D{lct}*(1+Assumptions!$B$9)")
bl_load.number_format = USD
bl_load.font = F_SUB
for col in range(1, 9):
    ws.cell(row=lct, column=col).fill = FILL_TOT
    ws.cell(row=lct, column=col).border = BOX
r = lct + 2
notes = [
    "RAW vs BURDENED — assessment: these are base/pay rates, burden-EXCLUSIVE. Two tells:",
    "  1. The GL books burden (FICA, UI, WC, health, pension, benefits, vac/hol = $157.4K YTD) as separate",
    "     operating-expense lines, NOT inside Cost of Revenues. If the job-cost rate were fully loaded, that",
    "     burden would sit in COGS instead — it cannot be in both. So the rate feeding COGS is burden-free.",
    "  2. On the COINS internal-labor job (9715), PTO, holiday and sick hours are booked at the SAME per-person",
    "     rate. A fully-burdened rate would double-count fringe when vacation/holiday time is also charged at it.",
    "Therefore: loaded cost = raw × (1 + burden%), burden ≈ 33.8% blended (Assumptions!B9). Note the blend is",
    "approximate — health insurance is ~flat $/head (heavier on lower-paid staff) and payroll taxes cap on high",
    "earners, so true burden % is higher at the bottom of the roster and lower at the top.",
    "TO CONFIRM DEFINITIVELY: ask payroll/COINS admin what the standard cost rate includes, or reconcile the",
    "timesheet direct-labor total to the GL 'Labor-Design Services' line ($428.5K YTD).",
    "Cost rates cluster by grade (both Engineer IIIs = $107.60), a good validation. Taylor Nelson costs at the",
    "Engineer I rate ($77.16) despite the assumed Engineer II billing class — worth confirming.",
]
for note in notes:
    ws.cell(row=r, column=1, value=note).font = F_NOTE
    r += 1
widths(ws, {"A": 30, "B": 20, "C": 13, "D": 13, "E": 14, "F": 20, "G": 20, "H": 16})

# ============================================================== Baseline P&L
ws = wb.create_sheet("Baseline P&L")
title(ws, "CVR — Baseline P&L, January–June 2026 (all figures $K)",
      "Jan–May monthlies from the KPI report; June from the GL statements (cross-tied on Checks tab). COGS/OpEx derived Jan–May.")
MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
NM = len(MONTHS)
YTD_COL = 2 + NM  # H
header(ws, 4, list(range(1, YTD_COL + 1)), ["CVR ACTUALS ($K)"] + MONTHS + ["YTD"])
REV = [110.5, 96.8, 39.3, 94.6, 85.5, 124.4]
GP = [52.6, 24.2, -15.7, 33.7, -18.0, 45.8]
NI = [-41.7, -49.1, -98.8, -60.5, -54.5, -15.8]


def put_row(ws, r, label, values=None, formula=None, fmt=KFMT, font=None, derived=False, n=NM, ytd_col=YTD_COL):
    lab = ws.cell(row=r, column=1, value=label + (" (derived)" if derived else ""))
    if font:
        lab.font = font
    if derived:
        lab.font = F_FLAG
    for i in range(n):
        col = 2 + i
        if values is not None:
            c = ws.cell(row=r, column=col, value=values[i])
        else:
            c = ws.cell(row=r, column=col, value=formula(get_column_letter(col)))
        c.number_format = fmt
        c.border = BOX
    last = get_column_letter(1 + n)
    y = ws.cell(row=r, column=ytd_col, value=f"=SUM(B{r}:{last}{r})")
    y.number_format = fmt
    y.border = BOX
    y.fill = FILL_TOT
    return r + 1


r = 5
r = put_row(ws, r, "Revenue", values=REV, font=F_SUB)
r = put_row(ws, r, "Cost of Sales", formula=lambda L: f"={L}5-{L}7", derived=True)
gp_r = r
r = put_row(ws, r, "Gross Profit", values=GP, font=F_SUB)
c = ws.cell(row=r, column=1, value="Gross margin %")
for i in range(NM + 1):
    col = get_column_letter(2 + i) if i < NM else get_column_letter(YTD_COL)
    cc = ws.cell(row=r, column=(2 + i) if i < NM else YTD_COL, value=f"={col}{gp_r}/{col}5")
    cc.number_format = PCT
r += 1
opex_r = r
r = put_row(ws, r, "Operating Expenses", formula=lambda L: f"={L}{gp_r}-{L}{opex_r+1}", derived=True)
ni_row = r
r = put_row(ws, r, "Net Income / (Loss)", values=NI, font=F_SUB)
c = ws.cell(row=r, column=1, value="Net margin %")
for i in range(NM + 1):
    col = get_column_letter(2 + i) if i < NM else get_column_letter(YTD_COL)
    cc = ws.cell(row=r, column=(2 + i) if i < NM else YTD_COL, value=f"={col}{ni_row}/{col}5")
    cc.number_format = PCT
r += 2

header(ws, r, list(range(1, YTD_COL + 1)), ["BUDGET ($K, monthly = Δ of published YTD)"] + MONTHS + ["YTD"])
r += 1
BUD_REV_C = [169.1, 338.2, 507.3, 676.4, 845.5, 1014.6]
BUD_GP_C = [104.1, 208.2, 312.3, 416.5, 520.6, 624.7]
BUD_NI_C = [11.6, 23.2, 34.9, 46.5, 58.1, 69.7]


def monthly(cum):
    return [round(cum[0], 1)] + [round(b - a, 1) for a, b in zip(cum, cum[1:])]


bud_rev_row = r
r = put_row(ws, r, "Revenue — budget", values=monthly(BUD_REV_C))
bud_gp_row = r
r = put_row(ws, r, "Gross Profit — budget", values=monthly(BUD_GP_C))
bud_ni_row = r
r = put_row(ws, r, "Net Income — budget", values=monthly(BUD_NI_C))
r += 1
header(ws, r, [1, 2, 3, 4], ["VARIANCE — YTD ($K)", "Actual", "Budget", "Act − Bud"])
r += 1
ycol = get_column_letter(YTD_COL)
for label, act_row, bud_row in [("Revenue", 5, bud_rev_row), ("Gross Profit", gp_r, bud_gp_row),
                                ("Net Income", ni_row, bud_ni_row)]:
    ws.cell(row=r, column=1, value=label).border = BOX
    a = ws.cell(row=r, column=2, value=f"={ycol}{act_row}")
    bgt = ws.cell(row=r, column=3, value=f"={ycol}{bud_row}")
    d = ws.cell(row=r, column=4, value=f"=B{r}-C{r}")
    for cell in (a, bgt, d):
        cell.number_format = KFMT
        cell.border = BOX
    r += 1
ws.cell(row=r + 1, column=1,
        value=("June was the best month YTD: 36.8% gross margin and a near-breakeven operating result (−$9.8K "
               "before interest). Note the June budget expects 61.6% GP — the actual/budget gap is labor cost "
               "vs revenue (see Realization).")).font = F_NOTE
widths(ws, {"A": 34, "B": 10, "C": 10, "D": 10, "E": 10, "F": 10, "G": 10, "H": 11})

# ============================================================ GL Income Stmt
ws = wb.create_sheet("GL Income Stmt")
title(ws, "CVR Engineering — GL Income Statement, period ending 6/30/2026 (all figures $)",
      "Source: data/CVR_Financial_Statements_2026-06-30.pdf (COINS GL Reporter). This is the line-item structure Phase 2 forecasts against.")
header(ws, 4, list(range(1, 8)),
       ["Line", "Jun Actual", "Jun Budget", "Jun PY", "YTD Actual", "YTD Budget", "YTD PY"])

# (label, jun_act, jun_bud, jun_py, ytd_act, ytd_bud, ytd_py, style)
GL = [
    ("Sales-Design Services", 124360, 169094, 86705, 551013, 1014563, 399143, "sub"),
    ("Subcontract", 0, 0, 0, 0, 0, 218460, None),
    ("Labor-Design Services", 78573, 64980, 43947, 428498, 389882, 462051, None),
    ("Direct Cost of Revenues Earned", 78573, 64980, 43947, 428498, 389882, 680511, "sub"),
    ("Gross Profit", 45787, 104114, 42757, 122514, 624681, -281368, "sub"),
    ("Labor-Indirect", -6078, 22236, 41879, 36890, 133414, 86024, None),
    ("FICA Expense", 5841, 7003, 7460, 38930, 42018, 45315, None),
    ("Federal Unemployment Expense", 6, 37, 0, 184, 224, 407, None),
    ("State Unemployment Expense", 23, 209, 0, 324, 1252, 2298, None),
    ("Mileage Expense", 54, 0, 10, 188, 0, 96, None),
    ("Repair & Maint. Equip.", 16, 19, 343, 527, 114, 368, None),
    ("Fuel Expense", 33, 20, 34, 185, 121, 171, None),
    ("Licenses & Permits", 0, 183, 2, 423, 1100, 195, None),
    ("Machinery Rental", 56, 48, 63, 335, 285, 460, None),
    ("Safety Expense", 24, 70, 1, 408, 421, 64, None),
    ("General Insurance", 3444, 5000, 3821, 20900, 30000, 22865, None),
    ("Workers' Compensation Insurance", 867, 925, 1050, 5907, 5550, 6634, None),
    ("Accounting & Legal", 73, 402, 883, 2350, 2412, 3642, None),
    ("Advertising & Sales Promotion", 275, 113, 34, 578, 675, 335, None),
    ("Admin. Meals & Ent.-Deductible", 870, 1150, 405, 4131, 6900, 5234, None),
    ("Admin.-Travel & Mileage", 2619, 3650, 3093, 21700, 21900, 22067, None),
    ("Bank Charges", 134, 268, 144, 3213, 1611, 1318, None),
    ("Computer Consulting Fees", 5346, 5000, 6114, 36226, 30000, 43534, None),
    ("Computer-PC Hardware", 100, 417, 20, 1110, 2500, 9825, None),
    ("Computer-PC Software", 678, 2417, 101, 7244, 14500, 3073, None),
    ("Computer-Internet Services", 397, 167, 4, 3841, 1000, 1328, None),
    ("Contributions", 0, 31, 50, 28, 183, 677, None),
    ("Dues & Subscriptions", 27, 68, 6, 1274, 405, 591, None),
    ("Employee Pre-Emp. Physicals", 0, 0, 0, 0, 0, 617, None),
    ("Employee Training & Seminars", 99, 917, 1671, 3290, 5500, 4449, None),
    ("Employee Benefits", 10, 0, 492, 440, 0, 47934, None),
    ("Emp. Insurance-Group Health", 11422, 9900, 5738, 51606, 59400, 50837, None),
    ("Emp. Pension Expense", 4576, 4576, 4280, 27455, 27455, 25680, None),
    ("Employee Bonus-Office", 0, 3333, 6418, 140, 20000, 37418, None),
    ("Emp. Vac & Hol Pay-Office", 6424, 5280, 15042, 32570, 31679, 44993, None),
    ("Office Supplies Expense", 118, 550, 28, 1432, 3300, 1063, None),
    ("Office Equipment Rental Exp.", 19, 0, 33, 115, 0, 175, None),
    ("Repair & Maintenance-Building", 176, 68, 87, 2082, 407, 1020, None),
    ("Telephone", 648, 276, 468, 2931, 1653, 2799, None),
    ("Utilities", 75, 0, 0, 477, 0, 0, None),
    ("Tax-Other", 0, 917, 0, 32, 5502, 70, None),
    ("Corporate Overhead Allocation", 17250, 17250, 23083, 103500, 103500, 138498, None),
    ("Total Operating Expenses", 55620, 92497, 122857, 412964, 554982, 612073, "sub"),
    ("Operating Income (Loss)", -9832, 11617, -80100, -290450, 69699, -893441, "sub"),
    ("Interest Expense", 6013, 0, 4893, 30087, 0, 29100, None),
    ("Net Income (Loss)", -15845, 11617, -84993, -320537, 69699, -922542, "sub"),
]
r0 = 5
gl_rows = {}
for i, (label, *vals, style) in enumerate(GL):
    r = r0 + i
    gl_rows[label] = r
    lab = ws.cell(row=r, column=1, value=label)
    for j, v in enumerate(vals):
        c = ws.cell(row=r, column=2 + j, value=v)
        c.number_format = D0
        c.border = BOX
        if style == "sub":
            c.font = F_SUB
            c.fill = FILL_TOT
    if style == "sub":
        lab.font = F_SUB
        lab.fill = FILL_TOT
r = r0 + len(GL)
# OILI rows (computed)
oi = gl_rows["Operating Income (Loss)"]
ie = gl_rows["Interest Expense"]
rev = gl_rows["Sales-Design Services"]
ws.cell(row=r, column=1, value="OILI (Operating Income less Interest)").font = F_SUB
for j in range(6):
    col = get_column_letter(2 + j)
    c = ws.cell(row=r, column=2 + j, value=f"={col}{oi}-{col}{ie}")
    c.number_format = D0
    c.font = F_SUB
    c.border = BOX
r += 1
ws.cell(row=r, column=1, value="OILI return % (OILI ÷ revenue)").font = F_SUB
for j in range(6):
    col = get_column_letter(2 + j)
    c = ws.cell(row=r, column=2 + j, value=f"=IF({col}{rev}=0,\"n/a\",({col}{oi}-{col}{ie})/{col}{rev})")
    c.number_format = PCT
    c.font = F_SUB
    c.border = BOX
r += 2
for note in [
    "June Labor-Indirect is negative (−$6,078): a reclass/credit month — worth confirming with accounting.",
    "Budget carries no interest expense; actual interest (~$5K/mo) accrues on the $3.44M parent note, so OILI",
    "and Net Income diverge from budget by that amount even at budgeted operating performance.",
    "Prior year YTD included $218K subcontract cost at a −70% gross margin; 2026 has no subcontract activity.",
]:
    ws.cell(row=r, column=1, value=note).font = F_NOTE
    r += 1
widths(ws, {"A": 34, "B": 12, "C": 12, "D": 12, "E": 13, "F": 13, "G": 13})
GL_REV_ROW = rev
GL_LABOR_ROW = gl_rows["Labor-Design Services"]

# ============================================================== Balance Sheet
ws = wb.create_sheet("Balance Sheet")
title(ws, "CVR Engineering — Balance Sheet, 6/30/2026 (all figures $)",
      "Source: data/CVR_Financial_Statements_2026-06-30.pdf")
header(ws, 4, [1, 2, 3, 4], ["Line", "Current", "One Year Ago", "Annual Budget"])
BS = [
    ("ASSETS", None, None, None, "hdr"),
    ("Accounts Receivable-Trade", 139807, 46065, 30000, None),
    ("Prepaid Expenses", 2000, 0, 6000, None),
    ("Total Current Assets", 141807, 46065, 36000, "sub"),
    ("Fixed / ROU / Other Assets", 0, 0, 0, None),
    ("Total Assets", 141807, 46065, 36000, "sub"),
    ("LIABILITIES", None, None, None, "hdr"),
    ("Accounts Payable", 0, 340, 0, None),
    ("Accrued Payroll", 19598, 28388, 40000, None),
    ("Accrued PTO", 14049, 0, 10000, None),
    ("Accrued Bonus", 0, 38508, 54740, None),
    ("Accrued Insurance Payable", -19465, -14099, -5000, None),
    ("Accrued Health Insurance Payable", 7373, 2635, 5000, None),
    ("Accrued Interest Payable", 16104, 16681, 0, None),
    ("Accrued Pension", 13459, 32339, 15000, None),
    ("Payroll Withholdings & Taxes Payable", 1426, 2105, 2000, None),
    ("Total Current Liabilities", 52544, 106898, 121740, "sub"),
    ("Note Payable Parent", 3436622, 3401478, 2801685, None),
    ("Total Liabilities", 3489166, 3508376, 2923425, "sub"),
    ("EQUITY", None, None, None, "hdr"),
    ("Paid In Surplus", 500, 500, 500, None),
    ("Retained Earnings", -3027323, -2540270, -3027324, None),
    ("Net Income", -320537, -922542, 139399, None),
    ("Total Shareholders' Equity", -3347360, -3462311, -2887425, "sub"),
    ("Total Liabilities & Equity", 141807, 46065, 36000, "sub"),
]
r0 = 5
bs_rows = {}
for i, (label, cur, py, bud, style) in enumerate(BS):
    r = r0 + i
    bs_rows[label] = r
    lab = ws.cell(row=r, column=1, value=label)
    if style == "hdr":
        lab.font = F_SUB
        continue
    for j, v in enumerate((cur, py, bud)):
        c = ws.cell(row=r, column=2 + j, value=v)
        c.number_format = D0
        c.border = BOX
        if style == "sub":
            c.font = F_SUB
            c.fill = FILL_TOT
    if style == "sub":
        lab.font = F_SUB
r = r0 + len(BS) + 1
for note in [
    "CVR holds no cash, fixed assets, or leases — the balance sheet is essentially AR funded by the parent note.",
    "Cumulative deficit: retained earnings −$3.03M plus current-year loss = equity of −$3.35M. This is the",
    "historic cost of running engineering as a loss-leader, quantified — and the baseline the turnaround is measured against.",
    "AR tripled year-over-year ($46K → $140K), consistent with growing external billing activity.",
]:
    ws.cell(row=r, column=1, value=note).font = F_NOTE
    r += 1
widths(ws, {"A": 36, "B": 14, "C": 14, "D": 14})

# ====================================================== Cash Flow & Customers
ws = wb.create_sheet("Cash Flow & Customers")
title(ws, "Six-Month Cash Flow Summary and Sales by Customer (all figures $)",
      "Source: data/CVR_Financial_Statements_2026-06-30.pdf")
header(ws, 4, [1, 2, 3], ["Cash flow line", "Actual thru 6/30/26", "Budget thru 12/31/26"])
CF = [
    ("Net Income / (Loss)", -320537, 139399),
    ("Δ Accounts Receivable-Billed", -98921, 10886),
    ("Δ Prepaid Expenses", 4000, 0),
    ("Δ Accrued Expenses", -61697, 7497),
    ("Net Cash from Operating Activities", -477155, 157782),
    ("Net Increase/(Decrease) to Note Payable-USC", 477155, -157782),
    ("Net Change in Cash", 0, 0),
]
r = 5
for label, act, bud in CF:
    bold = label.startswith("Net Cash") or label.startswith("Net Change")
    lab = ws.cell(row=r, column=1, value=label)
    if bold:
        lab.font = F_SUB
    for j, v in enumerate((act, bud)):
        c = ws.cell(row=r, column=2 + j, value=v)
        c.number_format = D0
        c.border = BOX
        if bold:
            c.font = F_SUB
            c.fill = FILL_TOT
    r += 1
ws.cell(row=r + 1, column=1,
        value=("Every operating dollar CVR consumes is funded by drawing on the USC parent note — $477K drawn in "
               "six months. The full-year budget expects a $158K paydown, which requires the budgeted H2 swing to "
               "+$139K net income.")).font = F_NOTE
r += 3

ws.cell(row=r, column=1, value="SALES BY CUSTOMER — YTD 6/30/2026").font = F_SUB
r += 1
header(ws, r, [1, 2, 3, 4], ["Customer", "Sales $", "% of total", "Type"])
r += 1
CUST = [
    ("CenterPoint Energy (job 017-0001)", 383956, "external"),
    ("Hydaker Wheatlake — DTE-New Baltimore (001-0003)", 40187, "intercompany"),
    ("Hydaker Wheatlake — CE HVD Pole Replacement (005-0004)", 71268, "intercompany"),
    ("Ambor Structures (022-0003)", 19200, "external"),
    ("Steuben County REMC (019-0001)", 15300, "external"),
    ("Great Lakes Energy (021-0001)", 13377, "external"),
    ("Kokosing Industrial (005-0001)", 7725, "external"),
]
cust0 = r
for label, amt, typ in CUST:
    ws.cell(row=r, column=1, value=label).border = BOX
    c = ws.cell(row=r, column=2, value=amt)
    c.number_format = D0
    c.border = BOX
    p = ws.cell(row=r, column=3, value=f"=B{r}/$B${cust0 + len(CUST)}")
    p.number_format = PCT
    p.border = BOX
    t = ws.cell(row=r, column=4, value=typ)
    t.border = BOX
    t.font = F_NOTE
    r += 1
tot = r
ws.cell(row=r, column=1, value="Total").font = F_SUB
c = ws.cell(row=r, column=2, value=f"=SUM(B{cust0}:B{tot-1})")
c.number_format = D0
c.font = F_SUB
c.fill = FILL_TOT
c.border = BOX
r += 1
ic = ws.cell(row=r, column=1, value="Intercompany (HWC) share")
c = ws.cell(row=r, column=2, value=f"=(B{cust0+1}+B{cust0+2})/B{tot}")
c.number_format = PCT
r += 1
cp = ws.cell(row=r, column=1, value="CenterPoint share")
c = ws.cell(row=r, column=2, value=f"=B{cust0}/B{tot}")
c.number_format = PCT
r += 2
ws.cell(row=r, column=1,
        value=("Answers a Phase-1 question: CVR hours on HWC jobs ARE revenue-credited as intercompany sales "
               "(~20% of YTD revenue). CenterPoint is ~70% of revenue — matching its ~70% share of billable hours.")).font = F_NOTE
widths(ws, {"A": 52, "B": 16, "C": 12, "D": 14})
CUST_TOTAL_ROW = tot

# =========================================================== HWC EPC Baseline
ws = wb.create_sheet("HWC EPC Baseline")
title(ws, "HWC EPC — Baseline, January–May 2026 (all figures $K)",
      "Context for the engineering P&L: design quality and constructability directly affect these outcomes.")
EPC_M = ["Jan", "Feb", "Mar", "Apr", "May"]
header(ws, 4, list(range(1, 8)), ["HWC EPC ($K)"] + EPC_M + ["YTD"])
r = 5
r = put_row(ws, r, "Revenue", values=[732.2, 207.7, -321.0, -125.1, 678.6], font=F_SUB, n=5, ytd_col=7)
r = put_row(ws, r, "Net Profit / (Loss)", values=[-318.3, -346.9, -672.8, -656.5, -114.8], font=F_SUB, n=5, ytd_col=7)
c = ws.cell(row=r, column=1, value="Net margin % (YTD)")
cc = ws.cell(row=r, column=7, value="=G6/G5")
cc.number_format = PCT
r += 2
for note in [
    "Negative revenue in March and April are billing adjustments/write-downs per the KPI report charts.",
    "Active EPC scorecard jobs (7/11/2026): 4 substation projects, PO $4.3M–$6.6M, plan margins 12.7%–16.4%,",
    "cost variance +3.6% to −19.8%. Engineering share of paired EPC pursuits runs ~4–5% of EPC job value.",
]:
    ws.cell(row=r, column=1, value=note).font = F_NOTE
    r += 1
widths(ws, {"A": 30, "B": 10, "C": 10, "D": 10, "E": 10, "F": 10, "G": 11})

# ================================================================ Realization
ws = wb.create_sheet("Realization")
title(ws, "Realization Analysis — where does the rate card go?",
      "Compares billable-hour value at card rates against GL revenue through 6/30, plus the labor-multiplier view.")
header(ws, 4, [1, 2, 3], ["Step", "Value", "Source / formula"])
real_rows = [
    ("Billable hours YTD (through 7/11)", "='Roster & Hours'!I%d" % ROSTER_TOTAL_ROW, HRS,
     "Roster & Hours total (KPI report: 4,747)"),
    ("Adjustment factor to June 30", "=Assumptions!B8", '0.000', "Assumptions — aligns hours window to the GL period"),
    ("Est. billable hours, Jan–Jun", "=B5*B6", HRS, "calc"),
    ("Blended card rate ($/hr)", "='Roster & Hours'!D%d" % ROSTER_TOTAL_ROW, USD, "mix-weighted from actual billable hours"),
    ("Value at card rates, Jan–Jun ($K)", "=B7*B8/1000", KFMT, "calc"),
    ("Actual revenue, Jan–Jun ($K)", "='GL Income Stmt'!E%d/1000" % GL_REV_ROW, KFMT, "GL income statement"),
    ("Realization %", "=B10/B9", PCT, "actual ÷ card value"),
    ("Implied realized rate ($/hr)", "=B10*1000/B7", USD, "calc"),
    ("Unexplained gap ($K)", "=B9-B10", KFMT, "to be decomposed below"),
    ("Direct labor cost ($K, GL)", "='GL Income Stmt'!E%d/1000" % GL_LABOR_ROW, KFMT, "Labor-Design Services YTD"),
    ("Direct labor cost per billable hour", "=B14*1000/B7", USD, "calc"),
    ("Labor multiplier — actual (rev ÷ direct labor)", "=B10/B14", '0.00"x"', "GL YTD"),
    ("Labor multiplier — budget", "='GL Income Stmt'!F%d/'GL Income Stmt'!F%d" % (GL_REV_ROW, GL_LABOR_ROW),
     '0.00"x"', "budget assumes 2.60x; industry-healthy is ~2.5–3.0x"),
]
r = 5
for label, formula, fmt, src in real_rows:
    ws.cell(row=r, column=1, value=label).border = BOX
    c = ws.cell(row=r, column=2, value=formula)
    c.number_format = fmt
    c.border = BOX
    s = ws.cell(row=r, column=3, value=src)
    s.font = F_NOTE
    s.border = BOX
    r += 1
r += 1
ws.cell(row=r, column=1, value="Gap decomposition — fill after the finance review (must sum to the unexplained gap):").font = F_SUB
r += 1
decomp0 = r
for bucket in ["Unbilled WIP / billing lag ($K)", "Write-offs & discounts ($K)",
               "Intercompany work at reduced rates ($K)", "Other / unreconciled ($K)"]:
    ws.cell(row=r, column=1, value=bucket).border = BOX
    c = ws.cell(row=r, column=2, value=0)
    c.font = F_INPUT
    c.number_format = KFMT
    c.border = BOX
    r += 1
ws.cell(row=r, column=1, value="Decomposition vs gap")
c = ws.cell(row=r, column=2, value=f"=SUM(B{decomp0}:B{r-1})-B13")
c.number_format = KFMT
ws.cell(row=r, column=3, value="should be 0 when fully explained").font = F_NOTE
r += 3

ws.cell(row=r, column=1, value="Annualized revenue grid ($K) — current roster, utilization × realization").font = F_SUB
r += 1
grid_top = r
utils = [0.59, 0.65, 0.70, 0.75]
reals = [0.60, 0.75, 0.90, 1.00]
ws.cell(row=grid_top, column=1, value="Utilization ↓ / Realization →").font = F_NOTE
for j, real in enumerate(reals):
    c = ws.cell(row=grid_top, column=2 + j, value=real)
    c.number_format = PCT
    c.font = F_H
    c.fill = FILL_H
    c.border = BOX
for i, u in enumerate(utils):
    rr = grid_top + 1 + i
    c = ws.cell(row=rr, column=1, value=u)
    c.number_format = PCT
    c.font = F_H
    c.fill = FILL_H
    c.border = BOX
    for j in range(len(reals)):
        col = get_column_letter(2 + j)
        cell = ws.cell(
            row=rr, column=2 + j,
            value=(f"=Assumptions!B7*Assumptions!B5*$A{rr}*{col}${grid_top}*$B$8/1000"))
        cell.number_format = '#,##0'
        cell.border = BOX
r = grid_top + len(utils) + 2
for note in [
    "Grid = active billable FTEs × hrs/FTE-yr × utilization × realization × blended card rate, in $K.",
    "Bottom-right cell (75% util, 100% realization) is the current-roster ceiling; compare against the $6,000K",
    "Year-2 goal to size the hiring plan (Phase 2).",
    "Multiplier view: budget expects 2.60x revenue per direct-labor dollar; actual is running ~1.29x. Both",
    "realization (price) and labor cost per billable hour feed this — salary data will separate the two.",
]:
    ws.cell(row=r, column=1, value=note).font = F_NOTE
    r += 1
widths(ws, {"A": 44, "B": 13, "C": 13, "D": 13, "E": 13})

# ======================================================== Checks & Open Items
ws = wb.create_sheet("Checks & Open Items")
title(ws, "Tie-outs across the KPI report and GL statements, and open questions")
header(ws, 4, [1, 2, 3, 4], ["Check", "Model", "Source", "Status"])
checks = [
    ("CVR revenue YTD Jun ($K) vs GL", "='Baseline P&L'!H5", 551.0, 1.0),
    ("CVR gross profit YTD Jun ($K) vs GL", "='Baseline P&L'!H7", 122.5, 1.0),
    ("CVR net income YTD Jun ($K) vs GL", "='Baseline P&L'!H10", -320.5, 1.0),
    ("KPI Jan–May revenue ($K) vs GL (YTD−Jun)", "=SUM('Baseline P&L'!B5:F5)", 426.7, 1.0),
    ("KPI Jan–May net income ($K) vs GL (YTD−Jun)", "=SUM('Baseline P&L'!B10:F10)", -304.7, 1.0),
    ("Sales by customer sums to GL revenue ($)", "='Cash Flow & Customers'!B%d" % CUST_TOTAL_ROW, 551013, 2),
    ("Balance sheet balances (assets = L+E, $)", "='Balance Sheet'!B%d" % bs_rows["Total Assets"], 141807, 1),
    ("EPC revenue YTD May ($K)", "='HWC EPC Baseline'!G5", 1172.4, 1.0),
    ("EPC net profit YTD May ($K)", "='HWC EPC Baseline'!G6", -2109.3, 1.0),
    ("Billable hours YTD", "='Roster & Hours'!I%d" % ROSTER_TOTAL_ROW, 4747.0, 60),
]
r = 5
for label, formula, target, tol in checks:
    ws.cell(row=r, column=1, value=label).border = BOX
    m = ws.cell(row=r, column=2, value=formula)
    m.number_format = KFMT if abs(target) < 10000 else D0
    m.border = BOX
    t = ws.cell(row=r, column=3, value=target)
    t.number_format = KFMT if abs(target) < 10000 else D0
    t.border = BOX
    s = ws.cell(row=r, column=4, value=f'=IF(ABS(B{r}-C{r})<={tol},"TIES","CHECK")')
    s.border = BOX
    r += 1
ws.cell(row=r, column=1,
        value="Billable-hours tolerance is wider: ~193 hrs on the KPI page are not attributed to a named employee.").font = F_NOTE
r += 2
ws.cell(row=r, column=1, value="ANSWERED BY THE 6/30 GL STATEMENTS").font = F_SUB
r += 1
answered = [
    "Corporate overhead allocation: $17,250/month flat ($103,500 YTD), same in budget.",
    "Interest basis: ~$5K/month accruing on the $3.44M Note Payable-Parent; not budgeted.",
    "Intercompany treatment: CVR hours on HWC jobs are revenue-credited as intercompany sales (~20% of YTD revenue).",
    "Employment burden: ~33.8% of total wages, computed from GL burden lines (refine with salary detail).",
    "Subcontract usage: none in 2026 (PY carried $218K at a loss).",
    "Full-year budget: +$139.4K net income, requiring a strong H2 swing.",
]
for item in answered:
    ws.cell(row=r, column=1, value="✓ " + item)
    r += 1
r += 1
ws.cell(row=r, column=1, value="STILL OPEN (Phase 1 exit criteria)").font = F_SUB
r += 1
items = [
    "Finance: salaries by person (to split the multiplier gap between price/realization and labor cost per hour).",
    "Finance: what drives June's negative Labor-Indirect (−$6,078) — reclass or credit?",
    "Confirm billing classifications for Taylor Nelson and Kevin Metts (not on the org chart).",
    "Confirm billing classification used for VP Engineering time (assumed Principal Engineer).",
    "Tom Little, Erin Bryden, Patrick Nicholson show no hours on the KPI utilization page — confirm where their time goes.",
    "Decompose the realization gap (Realization tab) — intercompany pricing on the ~20% HWC share is the lead suspect.",
    "Confirm whether the intercompany rate for HWC work uses the standard card or a discounted schedule.",
]
for item in items:
    ws.cell(row=r, column=1, value="• " + item)
    r += 1
widths(ws, {"A": 90, "B": 14, "C": 14, "D": 10})

# ====================================================================== Charts
from openpyxl.chart import AreaChart, BarChart, LineChart, Reference
from openpyxl.chart.marker import Marker
from openpyxl.drawing.line import LineProperties

BLUE, GRAY, INKC = "2A78D6", "898781", "0B0B0B"

ws = wb.create_sheet("Charts")
title(ws, "Charts — wired to the data tabs",
      "Native Excel charts driven by cell values: edit the data tabs and these redraw. Data blocks feeding them start at row 40.")

# ---- chart data blocks (formulas -> live) ----
MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
ws.cell(row=40, column=1, value="CHART DATA — cumulative revenue ($K)").font = F_SUB
ws.cell(row=41, column=1, value="Month")
for j, m in enumerate(MO):
    ws.cell(row=41, column=2 + j, value=m + " 26")
ws.cell(row=42, column=1, value="Actual (cumulative)")
ws.cell(row=43, column=1, value="Plan (cumulative)")
ws.cell(row=44, column=1, value="Prior year (pace)")
for j in range(6):
    col = get_column_letter(2 + j)
    prev = get_column_letter(1 + j)
    ws.cell(row=42, column=2 + j,
            value=(f"='Baseline P&L'!{col}5" if j == 0 else f"={prev}42+'Baseline P&L'!{col}5"))
    ws.cell(row=43, column=2 + j,
            value=(f"='Baseline P&L'!{col}14" if j == 0 else f"={prev}43+'Baseline P&L'!{col}14"))
    ws.cell(row=44, column=2 + j, value=round(399.1 / 6 * (j + 1), 1))

ws.cell(row=46, column=1, value="CHART DATA — gross margin %").font = F_SUB
ws.cell(row=47, column=1, value="Gross margin %")
ws.cell(row=48, column=1, value="Budget assumption")
for j in range(6):
    col = get_column_letter(2 + j)
    ws.cell(row=47, column=2 + j, value=f"='Baseline P&L'!{col}8").number_format = PCT
    ws.cell(row=48, column=2 + j, value=0.6157).number_format = PCT

def _line(series, hex_, width=20000, dash=None):
    lp = LineProperties(solidFill=hex_, w=width)
    if dash:
        lp.prstDash = dash
    series.graphicalProperties.line = lp

# ---- 1. cumulative revenue: 3-series line ----
c = LineChart()
c.title = "Cumulative revenue — Actual vs Plan vs Prior Year ($K)"
c.height, c.width = 8.5, 17
cats = Reference(ws, min_col=2, max_col=7, min_row=41)
data = Reference(ws, min_col=1, max_col=7, min_row=42, max_row=44)
c.add_data(data, titles_from_data=True, from_rows=True)
c.set_categories(cats)
_line(c.series[0], BLUE, 28000)
_line(c.series[1], GRAY)
_line(c.series[2], GRAY, dash="dash")
for s in c.series:
    s.smooth = False
c.y_axis.title = "$K cumulative"
ws.add_chart(c, "A3")

# ---- 2. gross margin columns + budget line ----
bar = BarChart()
bar.type = "col"
bar.title = "Gross margin by month vs 61.6% budget assumption"
bar.height, bar.width = 8.5, 17
bar.add_data(Reference(ws, min_col=1, max_col=7, min_row=47), titles_from_data=True, from_rows=True)
bar.set_categories(cats)
bar.series[0].graphicalProperties.solidFill = BLUE
bar.y_axis.number_format = "0%"
bar.y_axis.scaling.min, bar.y_axis.scaling.max = -0.6, 0.8
ln = LineChart()
ln.add_data(Reference(ws, min_col=1, max_col=7, min_row=48), titles_from_data=True, from_rows=True)
ln.set_categories(cats)
_line(ln.series[0], GRAY, dash="dash")
ln.y_axis.axId = 200
ln.y_axis.scaling.min, ln.y_axis.scaling.max = -0.6, 0.8
ln.y_axis.delete = True
bar += ln
ws.add_chart(bar, "A21")

# ---- 3. utilization by person: columns + target markers ----
ub = BarChart()
ub.type = "col"
ub.title = "Billable utilization vs target, by person (YTD)"
ub.height, ub.width = 8.5, 17
ucats = Reference(ws2 := wb["Roster & Hours"], min_col=1, min_row=5, max_row=14)
ub.add_data(Reference(ws2, min_col=6, min_row=4, max_row=14), titles_from_data=True)
ub.set_categories(ucats)
ub.series[0].graphicalProperties.solidFill = BLUE
ub.y_axis.number_format = "0%"
ub.y_axis.scaling.min, ub.y_axis.scaling.max = 0, 1.05
tl = LineChart()
tl.add_data(Reference(ws2, min_col=10, min_row=4, max_row=14), titles_from_data=True)
tl.set_categories(ucats)
tl.series[0].graphicalProperties.line.noFill = True
tl.series[0].marker = Marker(symbol="dash", size=12)
tl.y_axis.axId = 210
tl.y_axis.scaling.min, tl.y_axis.scaling.max = 0, 1.05
tl.y_axis.delete = True
ub += tl
ws.add_chart(ub, "A39")

# ---- 4. sales by customer: horizontal bars ----
wcf = wb["Cash Flow & Customers"]
cb = BarChart()
cb.type = "bar"
cb.title = "Sales by customer — YTD June 2026 ($)"
cb.height, cb.width = 8.5, 17
c0 = CUST_TOTAL_ROW - 7
cb.add_data(Reference(wcf, min_col=2, min_row=c0, max_row=CUST_TOTAL_ROW - 1), titles_from_data=False)
cb.set_categories(Reference(wcf, min_col=1, min_row=c0, max_row=CUST_TOTAL_ROW - 1))
cb.series[0].graphicalProperties.solidFill = BLUE
cb.legend = None
ws.add_chart(cb, "A57")

widths(ws, {"A": 22})

os.makedirs("model", exist_ok=True)
out = "model/CVR_Model_Phase1_Baseline.xlsx"
wb.save(out)
print(f"wrote {out}")
